export const PERMISSIONS = {
  // Customers
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',

  // Companies
  COMPANIES_VIEW: 'companies.view',
  COMPANIES_MANAGE: 'companies.manage',

  // Lines
  LINES_VIEW: 'lines.view',
  LINES_CREATE: 'lines.create',
  LINES_EDIT: 'lines.edit',
  LINES_DELETE: 'lines.delete',

  // Inventory
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',

  // Sales
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_CANCEL: 'sales.cancel',

  // Payments
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_REVERSE: 'payments.reverse',

  // Monthly Charges
  MONTHLY_CHARGES_VIEW: 'monthly_charges.view',
  MONTHLY_CHARGES_MANAGE: 'monthly_charges.manage',

  // Treasury
  TREASURY_VIEW: 'treasury.view',
  TREASURY_CREATE: 'treasury.create',
  TREASURY_MANAGE: 'treasury.manage',

  // Expenses
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',

  // Daily Closing
  DAILY_CLOSING_VIEW: 'daily_closing.view',
  DAILY_CLOSING_MANAGE: 'daily_closing.manage',
  DAILY_CLOSING_REOPEN: 'daily_closing.reopen',

  // Reports
  REPORTS_VIEW: 'reports.view',

  // Users & Administration
  USERS_MANAGE: 'users.manage',
  SETTINGS_MANAGE: 'settings.manage',
  AUDIT_VIEW: 'audit.view',
  BACKUP_MANAGE: 'backup.manage',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  ACCOUNTANT: 'ACCOUNTANT',
  SALES: 'SALES',
  VIEWER: 'VIEWER',
} as const;

export type RoleKey = typeof ROLES[keyof typeof ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.LINES_VIEW,
    PERMISSIONS.LINES_CREATE,
    PERMISSIONS.LINES_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.MONTHLY_CHARGES_VIEW,
    PERMISSIONS.MONTHLY_CHARGES_MANAGE,
    PERMISSIONS.TREASURY_VIEW,
    PERMISSIONS.TREASURY_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.DAILY_CLOSING_VIEW,
    PERMISSIONS.DAILY_CLOSING_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.LINES_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_REVERSE,
    PERMISSIONS.MONTHLY_CHARGES_VIEW,
    PERMISSIONS.MONTHLY_CHARGES_MANAGE,
    PERMISSIONS.TREASURY_VIEW,
    PERMISSIONS.TREASURY_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.DAILY_CLOSING_VIEW,
    PERMISSIONS.DAILY_CLOSING_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.SALES]: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.LINES_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.MONTHLY_CHARGES_VIEW,
    PERMISSIONS.TREASURY_VIEW,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.LINES_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.MONTHLY_CHARGES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
